package io.quarkus.gizmo2.impl;

import java.lang.constant.ClassDesc;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.List;

import io.quarkus.gizmo2.GenericType;
import io.quarkus.gizmo2.This;
import io.quarkus.gizmo2.desc.FieldDesc;
import io.smallrye.classfile.CodeBuilder;

/**
 * An expression representing a {@code this} reference.
 * When used inside an inner class to reference an enclosing class's {@code this},
 * the generated bytecode automatically traverses the {@code this$N} field chain.
 */
public final class ThisExpr extends Item implements This {
    private final TypeCreatorImpl creator;

    /**
     * Construct a new {@code this} expression.
     *
     * @param creator the type creator that owns this {@code this} expression (must not be {@code null})
     * @param type the class descriptor of the owning type (must not be {@code null})
     * @param genericType the generic type, or {@code null} if not generic
     */
    public ThisExpr(final TypeCreatorImpl creator, final ClassDesc type, final GenericType genericType) {
        super(type, genericType);
        this.creator = creator;
    }

    public boolean bound() {
        return false;
    }

    public void writeCode(final CodeBuilder cb, final BlockCreatorImpl block, final StackMapBuilder smb) {
        TypeCreatorImpl blockOwner = block.owner();
        if (creator == blockOwner) {
            // same class: simple aload(0)
            cb.aload(0);
            smb.push(type());
            smb.wroteCode();
        } else {
            // different class: walk the enclosing type chain and emit getfield chain
            List<FieldDesc> chain = resolveOuterChain(blockOwner);
            cb.aload(0);
            smb.push(blockOwner.type());
            for (FieldDesc fd : chain) {
                cb.getfield(fd.owner(), fd.name(), fd.type());
                smb.pop();
                smb.push(fd.type());
            }
            smb.wroteCode();
        }
    }

    /**
     * Walk from the given block owner up through the enclosing type chain
     * until we reach this expression's creator, collecting the {@code this$N}
     * field descriptors at each inner class step.
     *
     * @param blockOwner the type creator that owns the block being generated
     * @return the list of field descriptors to traverse, in order (not empty)
     * @throws IllegalStateException if the creator is not reachable from the block owner
     */
    private List<FieldDesc> resolveOuterChain(TypeCreatorImpl blockOwner) {
        ArrayList<FieldDesc> chain = new ArrayList<>(2);
        TypeCreatorImpl cur = blockOwner;
        while (cur != creator) {
            if (cur instanceof MemberClassCreatorImpl mcci && !Modifier.isStatic(mcci.modifiers)) {
                chain.add(mcci.outerFieldDesc());
                cur = cur.enclosingType();
            } else {
                throw new IllegalStateException(
                        "Enclosing this of %s is not reachable from %s (static or non-inner boundary encountered)"
                                .formatted(creator.type().displayName(), blockOwner.type().displayName()));
            }
        }
        return chain;
    }

    public String name() {
        return "this";
    }

    public String itemName() {
        return "this";
    }

    /** {@inheritDoc} */
    @Override
    protected StringBuilder appendSourceExpr(StringBuilder buf, SourceBuilder sb) {
        return buf.append("this");
    }
}
