name: Gizmo CI

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

jobs:
  build:
    name: "Build with JDK ${{ matrix.java }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [ 11, 17 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dno-format
