name: Gizmo CI

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - '.github/project.yml'
  pull_request:

jobs:
  build:
    name: "Build with JDK 25"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 25
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 25

      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dno-format
